name: Build theme for WP sites

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Build the Docker image
        run: docker build . --file Dockerfile_build --tag zhp-pl:$(date +%s)

      - uses: actions/checkout@v3
        name: Extract theme
        run: docker run -v ${PWD}:/usr/dist zhp-pl:$(date +%s)